---
title: "download_1"
output:
  html_document: default
  pdf_document: default
  word_document: default
date: "2025-02-07"
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# Data download

Locusta, Harmonia, Plutella, Drosophila (set I)

<https://linkinghub.elsevier.com/retrieve/pii/S2589004224021230>

<https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP438365&o=biosample_s%3Aa%253Bacc_s%3Bacc_s%3Aa>

----

[https://www.cell.com/iscience/fulltext/S2589-0042(18)30072-5#fig1](https://www.cell.com/iscience/fulltext/S2589-0042(18)30072-5#fig1)

Blattella ssr -\> <https://www.ncbi.nlm.nih.gov/Traces/study/?acc=PRJNA389591&o=acc_s%3Aa>

"In *B. germanica*, the analyses were based on 22 mRNA libraries that were prepared in our laboratory, representing the following 11 stages (two replicates each): non-fertilized egg (NFE); 8, 24, 48, 144, and 312 hr after oviposition (ED0, ED1, ED2, ED6, and ED13); first, third, fifth, and sixth (last) nymphal instars (N1, N3, N5, and N6); and adult female ([Table S1](https://www.cell.com/iscience/fulltext/S2589-0042(18)30072-5#mmc1)). In total, we obtained 198,970,437 read pairs"

Drosophila (set II):

<https://www.ncbi.nlm.nih.gov/Traces/study/?acc=SRP001419&o=library_name_s%3Ad%3Bacc_s%3Aa>

"The RNA-seq dataset of *D. melanogaster* used in the comparisons (GEO: [GSE18068](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE18068)) comprises 22 libraries from 11 developmental stages (two replicates each) covering the entire embryo development (six sequential stages: 0--4 hr, 4--6 hr, 6--12 hr, 12--16 hr, 16--20 hr, 20--24 hr), the three larval stages (L1, L2, L3), the pupa, and the adult female. In postembryonic stages, we followed the correspondence *B. germanica* pre-last nymphal instars with *D. melanogaster* larvae, the last nymphal instar with the pupa ([Belles and Santos, 2014](https://www.cell.com/iscience/fulltext/S2589-0042(18)30072-5#)), and the respective adult female stages"

Triatoma rubrofasciata:

<https://doi.org/10.1186/s12864-025-11632-8>

3 replicates of egg, male and female adults, and 5 nymph instars

no descriptions (names) of SRR

## Locusta migratoria

Download fastq: mistake in the article's table -\> SRR ...28 (not two times ... 24)

<http://v2.insect-genome.com/Organism/3800> - 07.02.2025

```{bash}
#bzip2 -d Locusta_migratoria_v2.genome.fa.tar.bz2

#tar -xvf Locusta_migratoria_v2.genome.fa.tar
```

```{bash}
#mkdir hisat2_index

#hisat2-build Locusta_migratoria_v2.genome.fa hisat2_index/locusta_index
```

```{bash}
for bam in locusta_mapped/*.bam; do
    echo "### $(basename "$bam")"
    samtools flagstat "$bam"
    echo
done > flagstat_all.txt
```

MAPPING

56358973 + 0 in total (QC-passed reads + QC-failed reads)

38534890 + 0 primary

17824083 + 0 secondary

0 + 0 supplementary

0 + 0 duplicates

0 + 0 primary duplicates

52663285 + 0 mapped (93.44% : N/A)

34839202 + 0 primary mapped (90.41% : N/A)

38534890 + 0 paired in sequencing

19267445 + 0 read1

19267445 + 0 read2

32048576 + 0 properly paired (83.17% : N/A)

32732454 + 0 with itself and mate mapped

2106748 + 0 singletons (5.47% : N/A)

358542 + 0 with mate mapped to a different chr

283150 + 0 with mate mapped to a different chr (mapQ\>=5)

the counts didnt assign any reads -\> the files (bam and gff3) dont match each other in scaffolds names -\> changed now around 10-20% assigned -\> in gff3 there arent all scaffolds that are in bam

added -O and -M cause there's a lot of multimapping and some multi-overlapping -\> 15-50%

trying mapping with the other genome files - <http://v2.insect-genome.com/Organism/509>:

samtools flagstat locusta_mapped2/SRR24633462.bam

53255946 + 0 in total (QC-passed reads + QC-failed reads)

38534890 + 0 primary

14721056 + 0 secondary

0 + 0 supplementary

0 + 0 duplicates

0 + 0 primary duplicates

47610407 + 0 mapped (89.40% : N/A)

32889351 + 0 primary mapped (85.35% : N/A)

38534890 + 0 paired in sequencing

19267445 + 0 read1

19267445 + 0 read2

28949028 + 0 properly paired (75.12% : N/A)

29976502 + 0 with itself and mate mapped

2912849 + 0 singletons (7.56% : N/A)

850944 + 0 with mate mapped to a different chr

710534 + 0 with mate mapped to a different chr (mapQ\>=5)

-- there's more assigned alignments (50%) but worse mapping?

which to choose?: the first one

## Harmonia axyridis

<http://v2.insect-genome.com/Organism/418> - 04.03.2025

```{bash}
#bzip2 -d Harmonia_axyridis.genome.fa.tar.bz2

tar -xvf Harmonia_axyridis.genome.fa.tar

#indexing genome

mkdir harmonia_index_hisat

hisat2-build Harmonia_axyridis.genome.fa harmonia_index_hisat/harmonia_index
```

samtools flagstat harmonia_mapped/SRR24633544.bam

48920570 + 0 in total (QC-passed reads + QC-failed reads)

46625360 + 0 primary

2295210 + 0 secondary

0 + 0 supplementary

0 + 0 duplicates

0 + 0 primary duplicates

36337614 + 0 mapped (74.28% : N/A)

34042404 + 0 primary mapped (73.01% : N/A)

46625360 + 0 paired in sequencing

23312680 + 0 read1

23312680 + 0 read2

30762004 + 0 properly paired (65.98% : N/A)

31356432 + 0 with itself and mate mapped

2685972 + 0 singletons (5.76% : N/A)

446726 + 0 with mate mapped to a different chr

394563 + 0 with mate mapped to a different chr (mapQ\>=5)

counts -\> 50-70% assigned

## Plutella xylostella

<http://v2.insect-genome.com/Organism/646> 11.03.2025

```{bash}
bzip2 -d Plutella_xylostella.genome.fa.tar.bz2

tar -xvf Plutella_xylostella.genome.fa.tar

#indexing genome

mkdir plutella_index_hisat

hisat2-build Plutella_xylostella.genome.fa plutella_index_hisat/plutella_index
```

## Drosophila melanogaster

<http://v2.insect-genome.com/Organism/296>

```{bash}
bzip2 -d Drosophila_melanogaster.genome.fa.tar.bz2

tar -xvf Drosophila_melanogaster.genome.fa.tar

#indexing genome

mkdir drosophila_index_hisat

hisat2-build Drosophila_melanogaster.genome.fa drosophila_index_hisat/drosophila_index
```

## Blattella germanica

<http://v2.insect-genome.com/Organism/115>

```{bash}
bzip2 -d Blattella_germanica.genome.fa.tar.bz2

tar -xvf Blattella_germanica.genome.fa.tar

#indexing genome

mkdir blattella_index_hisat

hisat2-build Blattella_germanica.genome.fa blattella_index_hisat/blattella_index
```

## Triatoma rubrofasciata

metadata is insufficient

<http://v2.insect-genome.com/Organism/767>

```{bash}
bzip2 -d Triatoma_rubrofasciata.genome.fa.tar.bz2

tar -xvf Triatoma_rubrofasciata.genome.fa.tar

#indexing genome

mkdir triatoma_index_hisat

hisat2-build Triatoma_rubrofasciata.genome.fa triatoma_index_hisat/triatoma_index
```
